"""Unit tests for the Assembly Builder's SysML physical view import.

The case that matters most is ``test_round_trip_through_the_export_renderer``:
the importer's whole reason to exist is reading what Export SysML Architecture
Document writes, so the fixture is generated by that renderer rather than typed
out here. A change to either side that breaks the pair fails this test.

Also pinned:

* ``test_a_leaf_classification_never_wins_over_real_children`` -- a ``part``
  node in the editor has no output port, so a definition labelled as a leaf
  that contains usages has to come back as an assembly or its children could
  not be attached.
* ``test_a_definition_that_contains_itself_does_not_recurse`` -- the cycle
  guard, since nothing stops a text file from describing one.
* ``test_multiplicity_above_one_is_reported_not_dropped`` -- Drawflow refuses a
  duplicate parent-to-child link, so quantities are collapsed; the user has to
  be told which ones.
"""

import importlib
from pathlib import Path

import pytest

PT_PKG = Path(__file__).resolve().parent.parent.name
sysml_import = importlib.import_module(
    f"{PT_PKG}.commands.assemblybuilder.sysml_import"
)
export_model = importlib.import_module(f"{PT_PKG}.commands.exportsysml.model")
export_render = importlib.import_module(f"{PT_PKG}.commands.exportsysml.render")


# ---------------------------------------------------------------------------
# Builders


def parse_graph(text):
    """Parse *text* and flatten it, the way ``entry.py`` does."""
    return sysml_import.to_graph(sysml_import.parse(text))


SIMPLE = """
package 'Gearbox Physical View' {
    private import ScalarValues::*;

    part def 'Housing' {
        attribute classification : String = "part";
        attribute bodyCount : Integer = 1;
    }

    part def 'Shaft' {
        attribute classification : String = "part";
        attribute bodyCount : Integer = 1;
    }

    part def 'Bearing Block' {
        attribute classification : String = "hybrid";
        attribute bodyCount : Integer = 1;

        part shaft : 'Shaft'[2];
    }

    part def 'Gearbox' {
        attribute classification : String = "subassembly";

        part housing : 'Housing';
        part bearingBlock : 'Bearing Block';
    }

    part gearbox : 'Gearbox';
}
"""


# ---------------------------------------------------------------------------
# strip_comments


def test_line_comments_are_removed():
    assert "secret" not in sysml_import.strip_comments("part def A; // secret")


def test_block_comments_are_removed():
    assert "secret" not in sysml_import.strip_comments("/* secret */ part def A;")


def test_a_doc_block_is_removed():
    text = "part def A {\n doc\n /* explanatory prose */\n }"
    assert "explanatory" not in sysml_import.strip_comments(text)


def test_comment_markers_inside_a_name_are_kept():
    """A component genuinely named with a slash must survive.

    The exporter quotes names, so ``'A // B'`` is a legal name and not a
    comment. Stripping it would silently rename the user's component.
    """
    text = "part def 'A // B' { }"
    assert "A // B" in sysml_import.strip_comments(text)


def test_comment_markers_inside_a_string_literal_are_kept():
    text = 'attribute description : String = "see /* spec */ page 4";'
    assert "see /* spec */ page 4" in sysml_import.strip_comments(text)


def test_an_unterminated_block_comment_does_not_hang():
    assert sysml_import.strip_comments("part def A; /* never closed") is not None


# ---------------------------------------------------------------------------
# unquote


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("Housing", "Housing"),
        ("'Housing'", "Housing"),
        ("'Bearing Block'", "Bearing Block"),
        ("'O\\'Brien'", "O'Brien"),
        ("'back\\\\slash'", "back\\slash"),
        ("Parts::Housing", "Housing"),
        ("  spaced  ", "spaced"),
        ("''", ""),
    ],
)
def test_names_are_unquoted_and_unescaped(raw, expected):
    assert sysml_import.unquote(raw) == expected


# ---------------------------------------------------------------------------
# parse


def test_the_package_name_is_captured():
    assert sysml_import.parse(SIMPLE).package_name == "Gearbox Physical View"


def test_every_definition_is_found():
    result = sysml_import.parse(SIMPLE)
    assert set(result.definitions) == {"Housing", "Shaft", "Bearing Block", "Gearbox"}


def test_the_top_level_usage_becomes_the_root():
    assert sysml_import.parse(SIMPLE).root == "Gearbox"


@pytest.mark.parametrize(
    ("name", "kind"),
    [
        ("Housing", sysml_import.KIND_PART),
        ("Shaft", sysml_import.KIND_PART),
        ("Bearing Block", sysml_import.KIND_HYBRID),
        ("Gearbox", sysml_import.KIND_ASSEMBLY),
    ],
)
def test_classification_maps_to_an_editor_node_type(name, kind):
    """``subassembly`` becomes ``assembly``; the editor has no third spelling."""
    assert sysml_import.parse(SIMPLE).definitions[name].kind == kind


def test_child_usages_carry_their_multiplicity():
    block = sysml_import.parse(SIMPLE).definitions["Bearing Block"]

    assert len(block.children) == 1
    assert block.children[0].type_name == "Shaft"
    assert block.children[0].count == 2
    assert block.children[0].usage_name == "shaft"


def test_a_usage_without_multiplicity_counts_as_one():
    gearbox = sysml_import.parse(SIMPLE).definitions["Gearbox"]
    assert [usage.count for usage in gearbox.children] == [1, 1]


def test_bare_identifier_names_parse_as_well_as_quoted_ones():
    """A model from another tool will not quote every name."""
    text = "package P { part def Housing { } part def Top { part h : Housing; } part t : Top; }"

    result = sysml_import.parse(text)

    assert result.root == "Top"
    assert result.definitions["Top"].children[0].type_name == "Housing"


def test_a_qualified_type_resolves_to_its_definition():
    text = (
        "package P { part def Housing { } "
        "part def Top { part h : Parts::Housing; } part t : Top; }"
    )

    graph = parse_graph(text)

    assert {edge["child"] for edge in graph.edges} == {"Housing"}


def test_unrecognised_statements_are_skipped_not_fatal():
    """Ports, constraints and requirements say nothing about composition."""
    text = """
    package P {
        private import ISQ::*;
        part def Housing {
            port fuelPort;
            attribute mass : Real = 1.5;
            constraint { mass > 0 }
        }
        part def Top { part h : Housing; }
        requirement def Stiffness;
        part t : Top;
    }
    """

    result = sysml_import.parse(text)

    assert result.root == "Top"
    assert "Housing" in result.definitions


def test_a_definition_with_no_body_is_recorded():
    text = "package P { part def Bracket; part def Top { part b : Bracket; } part t : Top; }"

    result = sysml_import.parse(text)

    assert "Bracket" in result.definitions
    assert result.definitions["Bracket"].kind == sysml_import.KIND_PART


def test_a_file_with_no_definitions_reports_why():
    result = sysml_import.parse("package Empty { }")

    assert result.root == ""
    assert any("no structure to import" in w.lower() for w in result.warnings)


def test_empty_input_is_not_an_error():
    result = sysml_import.parse("")
    assert result.root == ""
    assert result.definitions == {}


def test_a_duplicate_definition_name_is_reported():
    text = "package P { part def A { } part def A { } part def T { part a : A; } part t : T; }"

    result = sysml_import.parse(text)

    assert any("more than one definition" in w.lower() for w in result.warnings)


# ---------------------------------------------------------------------------
# Kind inference


def test_structure_infers_the_kind_without_a_classification():
    """A model from another tool carries no classification attribute."""
    text = (
        "package P { part def Leaf { } part def Top { part l : Leaf; } part t : Top; }"
    )

    result = sysml_import.parse(text)

    assert result.definitions["Top"].kind == sysml_import.KIND_ASSEMBLY
    assert result.definitions["Leaf"].kind == sysml_import.KIND_PART


def test_bodies_plus_children_infer_hybrid_without_a_classification():
    text = """
    package P {
        part def Leaf { }
        part def Top { attribute bodyCount : Integer = 2; part l : Leaf; }
        part t : Top;
    }
    """

    assert sysml_import.parse(text).definitions["Top"].kind == sysml_import.KIND_HYBRID


def test_a_leaf_classification_never_wins_over_real_children():
    """A part node has no output port, so its children could not attach.

    A file can contradict itself -- claim a leaf while nesting usages. The
    structure has to win, or the import produces a node whose children are
    silently unconnectable.
    """
    text = """
    package P {
        part def Leaf { }
        part def Top { attribute classification : String = "part"; part l : Leaf; }
        part t : Top;
    }
    """

    result = sysml_import.parse(text)

    assert result.definitions["Top"].kind == sysml_import.KIND_ASSEMBLY
    assert parse_graph(text).edges == [{"parent": "Top", "child": "Leaf"}]


def test_an_unknown_classification_falls_back_to_the_structure():
    text = """
    package P {
        part def Leaf { attribute classification : String = "widget"; }
        part def Top { part l : Leaf; }
        part t : Top;
    }
    """

    assert sysml_import.parse(text).definitions["Leaf"].kind == sysml_import.KIND_PART


# ---------------------------------------------------------------------------
# Root selection


def test_the_root_is_inferred_when_no_top_level_usage_exists():
    text = "package P { part def Top { part l : Leaf; } part def Leaf { } }"

    result = sysml_import.parse(text)

    assert result.root == "Top"
    assert any("no top-level part usage" in w.lower() for w in result.warnings)


def test_several_top_level_usages_pick_the_first_and_warn():
    text = "package P { part def A { } part def B { } part a : A; part b : B; }"

    result = sysml_import.parse(text)

    assert result.root == "A"
    assert any("top-level components" in w for w in result.warnings)


def test_a_fully_cyclic_model_still_yields_a_root():
    text = "package P { part def A { part b : B; } part def B { part a : A; } }"

    result = sysml_import.parse(text)

    assert result.root in {"A", "B"}
    assert any("cyclic" in w.lower() for w in result.warnings)


# ---------------------------------------------------------------------------
# to_graph


def test_the_graph_has_one_node_per_unique_component():
    graph = parse_graph(SIMPLE)

    assert [node["key"] for node in graph.nodes] == [
        "Gearbox",
        "Housing",
        "Bearing Block",
        "Shaft",
    ]
    assert graph.root_key == "Gearbox"


def test_the_root_node_is_flagged_so_the_editor_can_reuse_its_own():
    graph = parse_graph(SIMPLE)

    roots = [node for node in graph.nodes if node["isRoot"]]

    assert len(roots) == 1
    assert roots[0]["key"] == "Gearbox"


def test_edges_follow_containment():
    graph = parse_graph(SIMPLE)

    assert graph.edges == [
        {"parent": "Gearbox", "child": "Housing"},
        {"parent": "Gearbox", "child": "Bearing Block"},
        {"parent": "Bearing Block", "child": "Shaft"},
    ]


def test_multiplicity_above_one_is_reported_not_dropped():
    """Drawflow dedupes a repeated parent-to-child link, so it is collapsed.

    The link still has to exist once, and the user has to learn that the count
    did not survive -- otherwise they build an assembly they believe matches
    the model and it is short two shafts.
    """
    graph = parse_graph(SIMPLE)

    assert {"parent": "Bearing Block", "child": "Shaft"} in graph.edges
    assert graph.collapsed == ["2 x Shaft in Bearing Block"]
    assert "2 x Shaft" in sysml_import.summarize(graph)


def test_a_shared_component_keeps_both_parents():
    """Two parents is how the editor represents a reused component."""
    text = """
    package P {
        part def Pin { }
        part def Left { part p : Pin; }
        part def Right { part p : Pin; }
        part def Top { part l : Left; part r : Right; }
        part t : Top;
    }
    """

    graph = parse_graph(text)

    assert {"parent": "Left", "child": "Pin"} in graph.edges
    assert {"parent": "Right", "child": "Pin"} in graph.edges
    assert len([n for n in graph.nodes if n["key"] == "Pin"]) == 1
    assert "Shared components (more than one parent): 1" in sysml_import.summarize(
        graph
    )


def test_a_repeated_edge_is_emitted_once():
    text = """
    package P {
        part def Pin { }
        part def Top { part a : Pin; part b : Pin; }
        part t : Top;
    }
    """

    graph = parse_graph(text)

    assert graph.edges == [{"parent": "Top", "child": "Pin"}]


def test_a_definition_that_contains_itself_does_not_recurse():
    text = """
    package P {
        part def Loop { part inner : Loop; }
        part def Top { part l : Loop; }
        part t : Top;
    }
    """

    graph = parse_graph(text)

    assert {"parent": "Top", "child": "Loop"} in graph.edges
    assert {"parent": "Loop", "child": "Loop"} not in graph.edges
    assert any("contains itself" in w for w in graph.warnings)


def test_mutual_containment_terminates():
    text = """
    package P {
        part def A { part b : B; }
        part def B { part a : A; }
        part def Top { part a : A; }
        part t : Top;
    }
    """

    graph = parse_graph(text)

    assert graph.root_key == "Top"
    assert len(graph.nodes) == 3


def test_a_usage_of_an_undefined_type_is_reported():
    text = "package P { part def Top { part ghost : Missing; } part t : Top; }"

    graph = parse_graph(text)

    assert graph.edges == []
    assert any("Missing" in item for item in graph.skipped)
    assert "Not imported:" in sysml_import.summarize(graph)


def test_a_component_the_root_does_not_contain_is_skipped():
    """The creation pass only walks down from the root.

    An unreachable definition would arrive as a node wired to nothing and would
    never be built, so it is reported rather than quietly added.
    """
    text = """
    package P {
        part def Orphan { }
        part def Top { }
        part t : Top;
    }
    """

    graph = parse_graph(text)

    assert [node["key"] for node in graph.nodes] == ["Top"]
    assert any("Orphan" in item for item in graph.skipped)


def test_an_external_reference_is_carried_through_and_reported():
    text = """
    package P {
        part def Bought { attribute isExternalReference : Boolean = true; }
        part def Top { part b : Bought; }
        part t : Top;
    }
    """

    graph = parse_graph(text)
    summary = sysml_import.summarize(graph)

    assert [n["isExternalReference"] for n in graph.nodes if n["key"] == "Bought"] == [
        True
    ]
    assert "linked from other documents" in summary


def test_an_unparseable_file_summarises_the_failure():
    graph = parse_graph("this is not a model at all")

    assert graph.root_key == ""
    assert graph.nodes == []
    assert "No component structure" in sysml_import.summarize(graph)


def test_every_node_kind_is_one_the_editor_knows():
    graph = parse_graph(SIMPLE)

    assert {node["kind"] for node in graph.nodes} <= {
        sysml_import.KIND_PART,
        sysml_import.KIND_ASSEMBLY,
        sysml_import.KIND_HYBRID,
    }


def test_no_edge_points_at_a_part_node():
    """A part node has no output port, so it can never be a parent."""
    graph = parse_graph(SIMPLE)
    kinds = {node["key"]: node["kind"] for node in graph.nodes}

    for edge in graph.edges:
        assert kinds[edge["parent"]] != sysml_import.KIND_PART, edge


# ---------------------------------------------------------------------------
# Round trip against the exporter


def test_round_trip_through_the_export_renderer():
    """What Export SysML writes is what this import reads.

    The fixture is generated rather than transcribed, so a change to either the
    emitter or the parser that breaks the pair fails here.
    """
    node = export_model.CompNode
    child = export_model.ChildRef
    nodes = [
        node(
            key="k-top",
            name="Gearbox",
            children=(child("k-hsg", 1), child("k-blk", 2)),
            mass_kg=3.7,
        ),
        node(key="k-hsg", name="Housing (cast)", body_count=1, part_number="PN-1001"),
        node(
            key="k-blk",
            name="Bearing Block",
            body_count=1,
            children=(child("k-shf", 2),),
            is_referenced=True,
        ),
        node(key="k-shf", name="Shaft", body_count=1),
    ]
    assembly = export_model.AssemblyModel(
        meta=export_model.DocMeta(document_name="Gearbox", version=7),
        root_key="k-top",
        nodes={n.key: n for n in nodes},
        joints=(
            export_model.JointEdge(
                name="Pivot",
                joint_type="Revolute",
                owner_key="k-top",
                one_key="k-hsg",
                two_key="k-blk",
            ),
        ),
    )

    text = export_render.sysml_document(assembly)
    graph = parse_graph(text)

    assert graph.root_key == "Gearbox"
    assert {n["key"] for n in graph.nodes} == {
        "Gearbox",
        "Housing (cast)",
        "Bearing Block",
        "Shaft",
    }
    assert graph.edges == [
        {"parent": "Gearbox", "child": "Housing (cast)"},
        {"parent": "Gearbox", "child": "Bearing Block"},
        {"parent": "Bearing Block", "child": "Shaft"},
    ]
    kinds = {n["key"]: n["kind"] for n in graph.nodes}
    assert kinds["Gearbox"] == sysml_import.KIND_ASSEMBLY
    assert kinds["Bearing Block"] == sysml_import.KIND_HYBRID
    assert kinds["Housing (cast)"] == sysml_import.KIND_PART
    assert sorted(graph.collapsed) == [
        "2 x Bearing Block in Gearbox",
        "2 x Shaft in Bearing Block",
    ]
    assert graph.skipped == []
    # The emitter's own joint schema must not import as components. The node-set
    # assertion above is what catches it: `abstract part def FusionComponent`
    # escapes _PART_DEF_RE only because the line starts with the modifier.
    assert "FusionComponent" in text
    assert "FusionComponent" not in {n["key"] for n in graph.nodes}


def test_round_trip_preserves_a_name_that_needed_quoting():
    """Names with spaces, quotes and colons survive the emit-and-read cycle."""
    node = export_model.CompNode
    child = export_model.ChildRef
    hostile = "O'Brien's Bracket (v2): rev/A"
    nodes = [
        node(key="root", name="Top", children=(child("odd", 1),)),
        node(key="odd", name=hostile, body_count=1),
    ]
    assembly = export_model.AssemblyModel(
        meta=export_model.DocMeta(document_name="D"),
        root_key="root",
        nodes={n.key: n for n in nodes},
    )

    graph = parse_graph(export_render.sysml_document(assembly))

    assert {n["name"] for n in graph.nodes} == {"Top", hostile}
    assert graph.edges == [{"parent": "Top", "child": hostile}]


def test_round_trip_of_a_single_child_assembly_reports_nothing_lost():
    node = export_model.CompNode
    child = export_model.ChildRef
    nodes = [
        node(key="root", name="Top", children=(child("leaf", 1),)),
        node(key="leaf", name="Leaf", body_count=1),
    ]
    assembly = export_model.AssemblyModel(
        meta=export_model.DocMeta(document_name="D"),
        root_key="root",
        nodes={n.key: n for n in nodes},
    )

    graph = parse_graph(export_render.sysml_document(assembly))
    summary = sysml_import.summarize(graph)

    assert graph.collapsed == []
    assert graph.skipped == []
    assert graph.warnings == []
    assert "Not imported" not in summary
    assert "Imported 2 components" in summary


# ---------------------------------------------------------------------------
# The Fusion-facing half


entry = importlib.import_module(f"{PT_PKG}.commands.assemblybuilder.entry")
ENTRY_SOURCE = (
    Path(__file__).resolve().parent.parent / "commands" / "assemblybuilder" / "entry.py"
)
PALETTE_HTML = (
    Path(__file__).resolve().parent.parent
    / "commands"
    / "assemblybuilder"
    / "resources"
    / "html"
    / "index.html"
)


def test_a_utf8_file_is_read_as_utf8(tmp_path):
    """The export command writes UTF-8, so that is tried first."""
    path = tmp_path / "m.sysml"
    path.write_text("part def 'Halterung Ø12';", encoding="utf-8")

    assert "Ø12" in entry._read_sysml_text(str(path))


def test_a_byte_order_mark_is_stripped(tmp_path):
    """A BOM would otherwise become part of the first keyword."""
    path = tmp_path / "m.sysml"
    path.write_bytes("package P { }".encode("utf-8-sig"))

    assert entry._read_sysml_text(str(path)).startswith("package")


def test_a_non_utf8_file_falls_back_rather_than_refusing(tmp_path):
    """A model saved by another tool on Windows may be cp1252.

    Every byte maps under latin-1, so a mangled accent in one component name is
    a better outcome than refusing the whole import.
    """
    path = tmp_path / "m.sysml"
    path.write_bytes(b"part def 'Halterung \xd812';")

    assert entry._read_sysml_text(str(path)).startswith("part def")


def test_the_palette_dispatches_the_import_action():
    """The page's message and the handler's action string have to agree."""
    source = ENTRY_SOURCE.read_text(encoding="utf-8")
    page = PALETTE_HTML.read_text(encoding="utf-8")

    assert 'message_action == "importSysml"' in source
    assert "adsk.fusionSendData('importSysml'" in page


def test_the_graph_push_action_matches_the_page_handler():
    source = ENTRY_SOURCE.read_text(encoding="utf-8")
    page = PALETTE_HTML.read_text(encoding="utf-8")

    assert '"applySysmlGraph"' in source
    assert "action === 'applySysmlGraph'" in page
    assert "window.importSysml" in page
    assert 'onclick="importSysml()"' in page


def test_every_kind_the_parser_emits_is_a_node_type_the_page_defines():
    """A kind the editor does not know would silently become a part."""
    page = PALETTE_HTML.read_text(encoding="utf-8")

    for kind in (
        sysml_import.KIND_PART,
        sysml_import.KIND_ASSEMBLY,
        sysml_import.KIND_HYBRID,
    ):
        assert f"{kind}: {{ type:" in page, kind


def test_the_parser_kinds_match_the_creation_intent_map():
    """The same keys drive the node type and the Fusion design intent."""
    assert set(entry.INTENT_MAP) == {
        sysml_import.KIND_PART,
        sysml_import.KIND_ASSEMBLY,
        sysml_import.KIND_HYBRID,
    }


# ---------------------------------------------------------------------------
# Composition expressed in the usage tree
#
# A hand-authored physical architecture nests usages under a single top-level
# usage rather than putting children inside each definition. The first version
# of this parser only read the definition form and imported one node out of
# fifty-two from a real model. This fixture is a trimmed excerpt of that file,
# keeping every construct that broke it.


USAGE_TREE = """
package Stakeholders {
    part def Role;
    part chiefEngineer : Role;
    part mechanicalLead : Role;
}

package Materials {
    item def Material;
    item pa6gf30 : Material;
    item al6082T6 : Material;
}

package Components {
    part def PhysicalItem {
        ref item primaryMaterial : Material[0..1];
    }
    part def MowerProduct :> PhysicalItem;
    part def MowerAssembly :> PhysicalItem;
    part def ChassisAssembly :> PhysicalItem;
    part def ChassisFrame :> PhysicalItem;
    part def MotorMountBracket :> PhysicalItem;
    part def DockingStationAssembly :> PhysicalItem;
}

package Structure {
    private import Components::*;

    part rm500 : MowerProduct {
        @ConfigurationItem {
            partNumber = "RM500-000";
            revision = "A";
        }
        attribute :>> selfMass = 0.0 [kg];

        part mower : MowerAssembly :> subItems {
            attribute :>> envelopeLength = 630 [mm];

            part chassis : ChassisAssembly :> subItems {
                part frame : ChassisFrame :> subItems {
                    attribute :>> selfMass = 1.35 [kg];
                    ref item :>> primaryMaterial = pa6gf30;
                }
                part motorMounts : MotorMountBracket[2] :> subItems {
                    ref item :>> primaryMaterial = al6082T6;
                }
            }
        }

        part dock : DockingStationAssembly :> subItems {
            attribute :>> selfMass = 2.90 [kg];
        }

        interface mowerToDock : DockChargeInterface
            connect mower.dockContacts to dock.mowerContacts {
                attribute :>> alignmentTolerance = 15 [mm];
            }
    }
}
"""


def test_a_nested_usage_tree_is_read_as_composition():
    """``part a : A { part b : B; }`` means A contains B.

    This is the form a hand-authored physical architecture uses, and reading
    only the definition form imported a single node from a real 1300-line
    model.
    """
    graph = parse_graph(USAGE_TREE)

    assert graph.root_key == "MowerProduct"
    assert graph.edges == [
        {"parent": "MowerProduct", "child": "MowerAssembly"},
        {"parent": "MowerAssembly", "child": "ChassisAssembly"},
        {"parent": "ChassisAssembly", "child": "ChassisFrame"},
        {"parent": "ChassisAssembly", "child": "MotorMountBracket"},
        {"parent": "MowerProduct", "child": "DockingStationAssembly"},
    ]


def test_leaf_usages_of_a_contentless_type_do_not_become_the_root():
    """Eight ``part someRole : Role;`` lines are not the design.

    A stakeholder package contributes top-level usages that contain nothing.
    Choosing one would import a single empty node and silently discard the
    assembly, so a candidate with contents wins.
    """
    result = sysml_import.parse(USAGE_TREE)

    assert result.root == "MowerProduct"
    assert not any("Role" in w for w in result.warnings)


def test_items_are_not_imported_as_components():
    """``item pa6gf30 : Material`` is a material, not a part.

    SysML uses items for materials and for things that flow. Treating them as
    components would put glass-filled nylon in the assembly tree.
    """
    graph = parse_graph(USAGE_TREE)
    names = {node["key"] for node in graph.nodes}

    assert "Material" not in names
    assert "pa6gf30" not in names
    assert "al6082T6" not in names


def test_a_ref_item_redefinition_is_not_a_child():
    """``ref item :>> primaryMaterial = pa6gf30;`` binds a material."""
    graph = parse_graph(USAGE_TREE)

    assert all(edge["child"] != "Material" for edge in graph.edges)


def test_specialisation_in_a_usage_header_does_not_break_the_match():
    """``part mower : MowerAssembly :> subItems { ... }`` still reads as a usage."""
    graph = parse_graph(USAGE_TREE)

    assert {"parent": "MowerProduct", "child": "MowerAssembly"} in graph.edges


def test_metadata_annotations_are_skipped():
    """A ``@ConfigurationItem { partNumber = ...; }`` block holds no components.

    ``partNumber`` begins with the letters of ``part``, so a looser match would
    read it as a usage.
    """
    graph = parse_graph(USAGE_TREE)
    names = {node["key"] for node in graph.nodes}

    assert "partNumber" not in names
    assert len(names) == 6


def test_an_interface_body_contributes_no_components():
    graph = parse_graph(USAGE_TREE)
    names = {node["key"] for node in graph.nodes}

    assert "DockChargeInterface" not in names


def test_multiplicity_in_a_usage_tree_is_reported():
    graph = parse_graph(USAGE_TREE)

    assert graph.collapsed == ["2 x MotorMountBracket in ChassisAssembly"]


def test_definitions_with_no_body_are_still_components():
    """``part def MowerProduct :> PhysicalItem;`` declares a component."""
    result = sysml_import.parse(USAGE_TREE)

    assert "MowerProduct" in result.definitions
    assert result.definitions["MowerProduct"].is_declared


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        (None, 1),
        ("", 1),
        ("2", 2),
        (" 4 ", 4),
        ("2..4", 2),
        ("0..1", 1),
        ("0", 1),
        ("*", 1),
        ("1..*", 1),
    ],
)
def test_multiplicity_ranges_are_read_as_a_count(text, expected):
    """A range contributes its first bound, and zero is clamped to one.

    The editor cannot draw "sometimes present", so an optional component still
    gets its single link rather than disappearing.
    """
    assert sysml_import.multiplicity(text) == expected


def test_variation_points_are_left_out_and_reported():
    """A variant is a choice, not a fitted part.

    Importing every alternative would overstate the assembly -- the RM-500
    carries either an RTK mast or a wire receiver, never both.
    """
    text = """
    package P {
        part def Mast; part def Receiver; part def Base;
        part def Family {
            variation part guidance : Base {
                variant part rtkMast : Mast;
                variant part wireReceiver : Receiver;
            }
        }
        part def Top { part f : Family; }
        part t : Top;
    }
    """

    result = sysml_import.parse(text)
    graph = sysml_import.to_graph(result)

    assert {"parent": "Family", "child": "Mast"} not in graph.edges
    assert {"parent": "Family", "child": "Receiver"} not in graph.edges
    assert any("variation point" in w for w in result.warnings)


def test_a_short_name_alias_does_not_hide_the_declared_name():
    """``part def <'P-01'> Frame`` declares Frame, not P-01."""
    text = "package P { part def <'P-01'> Frame; part def Top { part f : Frame; } part t : Top; }"

    result = sysml_import.parse(text)

    assert "Frame" in result.definitions
    assert "P-01" not in result.definitions


def test_a_type_used_with_contents_but_never_defined_is_still_imported():
    """Dropping it would take its whole subtree with it."""
    text = """
    package P {
        part def Leaf;
        part top : UndeclaredTop {
            part l : Leaf;
        }
    }
    """

    result = sysml_import.parse(text)
    graph = sysml_import.to_graph(result)

    assert graph.root_key == "UndeclaredTop"
    assert {"parent": "UndeclaredTop", "child": "Leaf"} in graph.edges
    assert any("no 'part def'" in w for w in result.warnings)


def test_two_usages_of_one_type_under_one_owner_report_the_total():
    """The canvas holds one link per pair, so the counts have to be summed."""
    text = """
    package P {
        part def Bolt;
        part def Top { part a : Bolt[2]; part b : Bolt[3]; }
        part t : Top;
    }
    """

    graph = parse_graph(text)

    assert graph.edges == [{"parent": "Top", "child": "Bolt"}]
    assert graph.collapsed == ["5 x Bolt in Top"]


def test_a_long_summary_is_capped_so_the_dialog_stays_readable():
    """A message box past a couple of dozen lines gets dismissed, not read."""
    kids = " ".join(f"part p{i} : Leaf{i};" for i in range(40))
    defs = " ".join(f"part def Leaf{i};" for i in range(40))
    text = f"package P {{ {defs} part def Top {{ {kids} }} part t : Top; }}"

    graph = parse_graph(text)
    # Force a long list by treating every child as collapsed.
    graph.collapsed = [f"2 x Leaf{i} in Top" for i in range(40)]
    summary = sysml_import.summarize(graph)

    assert "... and 20 more" in summary
    assert summary.count("2 x Leaf") == sysml_import.SUMMARY_LIST_CAP
