# Copyright (C) Industrial Machine Arts LLC WA, USA - All Rights Reserved
#
# This source code is protected under international copyright law.  All rights
# reserved and protected by the copyright holders.
#
# This file is confidential and only available to authorized individuals with the
# permission of the copyright holders.  If you encounter this file and do not have
# permission, please contact the copyright holders and delete this file.

"""Design-intent icons (part / hybrid / assembly) shared by PowerTools palettes.

``assets/intent_icons`` holds the Fusion design-intent glyphs at 16 px and 32 px
for both UI themes, named ``<intent>-<size>-<theme>.svg``. They live beside
recents_utils — which already owns the ``part|hybrid|assembly`` vocabulary — so
every surface draws the same icon for the same intent.

Palette pages are loaded from a ``file://`` URL, so instead of having each
palette's CSS reach back across the add-in tree for these SVGs, ``stylesheet()``
returns a CSS body that carries them as data URIs in custom properties:

    :root      { --pt-intent-part-16: url("data:…"); … }   /* dark  */
    body.light { --pt-intent-part-16: url("data:…"); … }    /* light */

A palette writes that next to its index.html on open (see ``write_stylesheet``),
links it after its own stylesheet, then draws icons with
``background-image: var(--pt-intent-part-16)``. Because the output is fixed, the
file can be rewritten on every open without the stale-cache worries that make
generated init.js unreliable on Windows.
"""

import base64
import os
from functools import lru_cache

_ICON_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "assets", "intent_icons"
)

# Design intents that have an icon, matching recents_utils.DESIGN_INTENTS.
INTENTS = ("part", "hybrid", "assembly")

# 16 px for inline badges, 32 px for the thumbnail placeholder.
SIZES = (16, 32)

THEMES = ("dark", "light")


def css_var(intent: str, size: int) -> str:
    """Return the CSS custom-property name holding this icon, e.g.
    ``--pt-intent-part-16``. Theme selection is the stylesheet's job."""
    return f"--pt-intent-{intent}-{size}"


@lru_cache(maxsize=len(INTENTS) * len(SIZES) * len(THEMES))
def data_uri(intent: str, size: int = 16, theme: str = "dark") -> str:
    """Return a base64 ``data:`` URI for one intent icon, or "" if unavailable.

    Unknown intent/size/theme combinations return "" rather than raising, so a
    caller can pass a raw intent string straight through.
    """
    if intent not in INTENTS or size not in SIZES or theme not in THEMES:
        return ""
    path = os.path.join(_ICON_DIR, f"{intent}-{size}-{theme}.svg")
    try:
        with open(path, "rb") as fh:
            b64 = base64.b64encode(fh.read()).decode("ascii")
    except OSError:
        return ""
    return f"data:image/svg+xml;base64,{b64}"


def stylesheet() -> str:
    """Return a complete CSS file body defining every intent icon as a variable.

    Dark lands on ``:root`` and light on ``body.light``, mirroring how the
    palettes' own stylesheets declare their theme variables.
    """
    lines = [
        "/* Generated by lib/ptAddInUtils/intent_icons.py — do not edit by hand. */",
        "/* Design-intent icons as data URIs. Dark is the default; body.light",
        "   overrides it, matching each palette's own theme variable blocks. */",
    ]
    for theme in THEMES:
        lines.append("")
        lines.append(f"{':root' if theme == 'dark' else 'body.light'} {{")
        for intent in INTENTS:
            for size in SIZES:
                uri = data_uri(intent, size, theme)
                if uri:
                    lines.append(f'    {css_var(intent, size)}: url("{uri}");')
        lines.append("}")
    return "\n".join(lines) + "\n"


def write_stylesheet(path: str) -> bool:
    """Write ``stylesheet()`` to *path*. Returns False if the write failed."""
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(stylesheet())
    except OSError:
        return False
    return True
